In [1]:
import pandas as pd
import numpy as np

In [2]:
df_bili = pd.read_csv("./data/added_data_v3/bilibili_tcp_flow.csv")
df_bili.insert(loc=6, column='is_tcp', value='1')
df_bili_u = pd.read_csv("./data/added_data_v3/bilibili_udp_flow.csv")
df_bili_u.insert(loc=6, column='is_tcp', value='0')
df_bili = df_bili.append(df_bili_u)

df_skype = pd.read_csv("./data/added_data_v3/Skype_HongKong_tcp_flow.csv")
df_skype.insert(loc=6, column='is_tcp', value='1')
df_skype_u = pd.read_csv("./data/added_data_v3/Skype_HongKong_udp_flow.csv")
df_skype_u.insert(loc=6, column='is_tcp', value='0')
df_skype = df_skype.append(df_skype_u)

df_download = pd.read_csv("./data/added_data_v3/APP_DOWNLOAD_tcp_flow.csv")
df_download.insert(loc=6, column='is_tcp', value='1')
df_download_u = pd.read_csv("./data/added_data_v3/APP_DOWNLOAD_udp_flow.csv")
df_download_u.insert(loc=6, column='is_tcp', value='0')
df_download = df_download.append(df_download_u)

df_LoL = pd.read_csv("./data/added_data_v3/LOL_AI_tcp_flow.csv")
df_LoL.insert(loc=6, column='is_tcp', value='1')
df_LoL_u = pd.read_csv("./data/added_data_v3/LOL_AI_udp_flow.csv")
df_LoL_u.insert(loc=6, column='is_tcp', value='0')
df_LoL = df_LoL.append(df_LoL_u)

df_netease = pd.read_csv("./data/added_data_v3/netease_game_tcp_flow.csv")
df_netease.insert(loc=6, column='is_tcp', value='1')
df_netease_u = pd.read_csv("./data/added_data_v3/netease_game_udp_flow.csv")
df_netease_u.insert(loc=6, column='is_tcp', value='0')
df_netease = df_netease.append(df_netease_u)

df_youtube = pd.read_csv("./data/added_data_v3/youtube_tcp_flow.csv")
df_youtube.insert(loc=6, column='is_tcp', value='1')
df_youtube_u = pd.read_csv("./data/added_data_v3/youtube_udp_flow.csv")
df_youtube_u.insert(loc=6, column='is_tcp', value='0')
df_youtube = df_youtube.append(df_youtube_u)

df_tencent = pd.read_csv("./data/added_data_v3/tencent_game_na_tcp_flow.csv")
df_tencent.insert(loc=6, column='is_tcp', value='1')
df_tencent_u = pd.read_csv("./data/added_data_v3/tencent_game_na_udp_flow.csv")
df_tencent_u.insert(loc=6, column='is_tcp', value='0')
df_tencent = df_tencent.append(df_tencent_u)

df_wechat = pd.read_csv("./data/added_data_v3/wechat_video_tcp_flow.csv")
df_wechat.insert(loc=6, column='is_tcp', value='1')
df_wechat_u = pd.read_csv("./data/added_data_v3/wechat_video_udp_flow.csv")
df_wechat_u.insert(loc=6, column='is_tcp', value='0')
df_wechat = df_wechat.append(df_wechat_u)

df_google = pd.read_csv("./data/added_data_v3/google_drive_download_tcp_flow.csv")
df_google.insert(loc=6, column='is_tcp', value='1')
df_google_u = pd.read_csv("./data/added_data_v3/google_drive_download_udp_flow.csv")
df_google_u.insert(loc=6, column='is_tcp', value='0')
df_google = df_google.append(df_google_u)

In [3]:
## name of output
output = "./concatenate_v3.csv"

In [4]:
print("Read {} rows.".format(len(df_google)))

Read 336 rows.

In [5]:
df_bili.head(5)

,avg(pkt_len),stddev(pkt_len),fb_ratio,inter_arrival_time,pkt_count,duration,is_tcp,tot_pkt_len,fwd_pkt_len,bwd_pkt_len
0,127.608696,200.746049,1.648917,0.258844,23,5.694573,1,2935.0,1827,1108.0
1,152.366667,322.643213,0.250445,3.683159,60,217.306407,1,9142.0,1831,7311.0
2,815.367807,635.379605,0.022415,0.001908,1286,2.452179,1,1048563.0,22988,1025575.0
3,56.514286,16.494833,-1.000000,2.581651,70,178.133886,1,3956.0,3956,0.0
4,124.041667,197.169642,1.593206,0.243110,24,5.591538,1,2977.0,1829,1148.0

In [6]:
df_bili.insert(loc=10, column='outcome', value='streaming')
df_skype.insert(loc=10, column='outcome', value='voip')
df_download.insert(loc=10, column='outcome', value='download')
df_LoL.insert(loc=10, column='outcome', value='game')
df_netease.insert(loc=10, column='outcome', value='game')
df_youtube.insert(loc=10, column='outcome', value='streaming')
df_tencent.insert(loc=10, column='outcome', value='game')
df_wechat.insert(loc=10, column='outcome', value='voip')
df_google.insert(loc=10, column='outcome', value='download')

In [7]:
df_concat = pd.concat([df_bili, df_skype, df_download, df_LoL, df_netease, df_youtube, df_tencent, df_wechat, df_google
                      ], ignore_index=True)

In [8]:
# df_1x.head(5)
print("Read {} rows.".format(len(df_concat)))
# print("Missing values:")
# print(format(df_google.isnull().sum()))

Read 4991 rows.

In [9]:
df_concat.head(5)

,avg(pkt_len),stddev(pkt_len),fb_ratio,inter_arrival_time,pkt_count,duration,is_tcp,tot_pkt_len,fwd_pkt_len,bwd_pkt_len,outcome
0,127.608696,200.746049,1.648917,0.258844,23,5.694573,1,2935.0,1827,1108.0,streaming
1,152.366667,322.643213,0.250445,3.683159,60,217.306407,1,9142.0,1831,7311.0,streaming
2,815.367807,635.379605,0.022415,0.001908,1286,2.452179,1,1048563.0,22988,1025575.0,streaming
3,56.514286,16.494833,-1.000000,2.581651,70,178.133886,1,3956.0,3956,0.0,streaming
4,124.041667,197.169642,1.593206,0.243110,24,5.591538,1,2977.0,1829,1148.0,streaming

In [10]:
# df_concat.to_csv(output)

In [11]:
df_voip = pd.concat([df_wechat, df_skype], ignore_index=True)
df_streaming = pd.concat([df_youtube, df_bili], ignore_index=True)
df_game = pd.concat([df_tencent, df_LoL, df_netease], ignore_index=True)
df_down = pd.concat([df_google, df_download], ignore_index=True)

In [12]:
# df_voip.to_csv("./voip.csv")
# df_streaming.to_csv("./streaming.csv")
# df_game.to_csv("./game.csv")
# df_down.to_csv("./download.csv")

In [13]:
df_voip = df_voip.drop(["is_tcp","outcome"],axis=1)
df_streaming = df_streaming.drop(["is_tcp","outcome"],axis=1)
df_game = df_game.drop(["is_tcp","outcome"],axis=1)
df_down = df_down.drop(["is_tcp","outcome"],axis=1)

In [14]:
df_down['pkt_count'] = df_down['pkt_count'].apply(pd.to_numeric)
df_down['fwd_pkt_len'] = df_down['fwd_pkt_len'].apply(pd.to_numeric)
df_game['pkt_count'] = df_game['pkt_count'].apply(pd.to_numeric)
df_game['fwd_pkt_len'] = df_game['fwd_pkt_len'].apply(pd.to_numeric)

In [39]:
df_voip.sample(n=10)

,avg(pkt_len),stddev(pkt_len),fb_ratio,inter_arrival_time,pkt_count,duration,tot_pkt_len,fwd_pkt_len,bwd_pkt_len
2717,37.000000,12.727922,1.642857,0.079883,2,0.079883,74.0,46.0,28.0
287,195.933333,371.472834,0.271744,0.014682,15,0.205554,2939.0,628.0,2311.0
1691,195.933333,371.472834,0.271744,0.014277,15,0.199881,2939.0,628.0,2311.0
883,195.933333,371.472834,0.271744,0.020669,15,0.289362,2939.0,628.0,2311.0
1987,195.933333,371.472834,0.271744,0.014716,15,0.206031,2939.0,628.0,2311.0
1681,195.933333,371.472834,0.271744,0.061610,15,0.862547,2939.0,628.0,2311.0
2112,183.370370,352.431352,0.431752,0.006295,27,0.163664,4951.0,1493.0,3458.0
1571,195.933333,371.472834,0.271744,0.017516,15,0.245221,2939.0,628.0,2311.0
2952,830.916733,349.902000,-1.000000,0.002800,1261,3.528123,1047786.0,1047786.0,0.0
1435,415.550000,593.108446,0.100503,0.039040,20,0.741756,8311.0,759.0,7552.0

In [16]:
df_down_mean=df_down.mean(axis=0)
df_down_std=df_down.std(axis=0)

df_game_mean=df_game.mean(axis=0)
df_game_std=df_game.std(axis=0)

df_streaming_mean=df_streaming.mean(axis=0)
df_streaming_std=df_streaming.std(axis=0)

df_voip_mean=df_voip.mean(axis=0)
df_voip_std=df_voip.std(axis=0)

In [17]:
df_down_des = df_down.describe(include='all')
df_streaming_des = df_streaming.describe()
df_voip_des = df_voip.describe()
df_game_des = df_game.describe()

In [37]:
df_streaming_des

,avg(pkt_len),stddev(pkt_len),fb_ratio,inter_arrival_time,pkt_count,duration,tot_pkt_len,fwd_pkt_len,bwd_pkt_len
count,498.000000,498.000000,498.000000,498.000000,498.000000,498.000000,4.980000e+02,4.980000e+02,4.980000e+02
mean,534.004716,184.387539,0.635512,1.728786,330.240964,30.115709,3.292141e+05,3.095242e+05,1.968989e+04
std,528.999148,163.803029,7.287837,14.278469,866.575546,92.786547,4.775557e+05,4.713752e+05,1.298630e+05
min,12.000000,-1.000000,-1.000000,-1.000000,1.000000,0.000000,1.600000e+01,1.600000e+01,0.000000e+00
25%,127.695652,38.425123,-1.000000,0.002193,5.000000,0.077916,5.550000e+02,2.380000e+02,0.000000e+00
50%,249.583333,130.880584,0.150869,0.009086,30.000000,1.715399,6.578000e+03,2.270500e+03,2.870000e+02
75%,1302.491925,311.025150,0.926486,0.187544,776.000000,6.231254,1.047651e+06,1.047532e+06,2.130250e+03
max,1352.000000,635.379605,130.212049,270.006957,11812.000000,510.944466,1.048563e+06,1.048551e+06,1.032668e+06

In [19]:
mean = pd.DataFrame(np.array([df_down_mean,
                              df_game_mean,
                              df_streaming_mean,
                              df_voip_mean
                             ]),
                   columns=["avg(pkt_len)",
                            "stddev(pkt_len)",
                            "fb_ratio",
                            "inter_arrival_time",
                            "pkt_count",
                            "duration",
                           "tot_pkt_len",
                           "fwd_pkt_len",
                           "bwd_pkt_len"])

mean = mean.rename({0: "download", 1: "game", 2: "streaming", 3: "voip"})

In [38]:
df_voip_des

,avg(pkt_len),stddev(pkt_len),fb_ratio,inter_arrival_time,pkt_count,duration,tot_pkt_len,fwd_pkt_len,bwd_pkt_len
count,3155.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3.155000e+03,3.155000e+03,3157.000000
mean,267.173337,337.310853,0.234405,1.726468,234.740893,19.205335,1.317886e+05,1.282395e+05,3546.862844
std,190.682305,169.220375,0.907612,25.363611,638.421930,123.444424,3.417302e+05,3.413618e+05,21525.883362
min,10.000000,-1.000000,-1.000000,-1.000000,1.000000,0.000000,2.000000e+01,2.000000e+01,0.000000
25%,195.933333,333.193521,0.100503,0.013648,15.000000,0.222905,2.939000e+03,6.280000e+02,192.000000
50%,195.933333,371.472834,0.271744,0.018369,15.000000,0.317899,2.939000e+03,6.280000e+02,2311.000000
75%,383.590909,371.472834,0.271744,0.055550,20.000000,1.696099,8.311000e+03,7.590000e+02,2311.000000
max,922.114035,717.982356,16.880000,899.245446,4207.000000,1712.837412,1.048575e+06,1.048575e+06,660960.000000

In [21]:
std = pd.DataFrame(np.array([df_down_std,
                              df_game_std,
                              df_streaming_std,
                              df_voip_std
                             ]),
                   columns=["avg(pkt_len)",
                            "stddev(pkt_len)",
                            "fb_ratio",
                            "inter_arrival_time",
                            "pkt_count",
                            "duration",
                            "tot_pkt_len",
                           "fwd_pkt_len",
                           "bwd_pkt_len"])

std = std.rename({0: "download", 1: "game", 2: "streaming", 3: "voip"})

In [33]:
mean

,avg(pkt_len),stddev(pkt_len),fb_ratio,inter_arrival_time,pkt_count,duration,tot_pkt_len,fwd_pkt_len,bwd_pkt_len
download,931.507567,113.091824,-0.410350,0.612753,572.876543,4.679878,663922.455418,654241.869684,9680.585734
game,238.455614,156.954309,0.202035,8.582993,314.545305,82.384577,103378.029654,41382.904448,61995.125206
streaming,534.004716,184.387539,0.635512,1.728786,330.240964,30.115709,329214.090361,309524.204819,19689.885542
voip,267.173337,337.310853,0.234405,1.726468,234.740893,19.205335,131788.606656,128239.495404,3546.862844

In [22]:
std

,avg(pkt_len),stddev(pkt_len),fb_ratio,inter_arrival_time,pkt_count,duration,tot_pkt_len,fwd_pkt_len,bwd_pkt_len
download,571.249398,192.515558,0.919789,5.094285,1076.409626,21.251615,500742.294263,504703.793849,89598.911892
game,294.843684,218.167267,1.185566,56.605510,1666.643723,256.675531,282090.971822,175601.879054,221980.381476
streaming,528.999148,163.803029,7.287837,14.278469,866.575546,92.786547,477555.698447,471375.227250,129863.027843
voip,190.682305,169.220375,0.907612,25.363611,638.421930,123.444424,341730.239415,341361.845571,21525.883362

In [23]:
df_game.corrwith(df_voip)

avg(pkt_len)          0.025837
stddev(pkt_len)       0.065221
fb_ratio              0.019417
inter_arrival_time    0.029667
pkt_count            -0.006191
duration              0.010463
tot_pkt_len          -0.017436
fwd_pkt_len          -0.001732
bwd_pkt_len          -0.015900
dtype: float64

In [24]:
df_voip.corrwith(df_down)

avg(pkt_len)         -0.109890
stddev(pkt_len)       0.068859
fb_ratio             -0.048364
inter_arrival_time   -0.011160
pkt_count            -0.013858
duration             -0.023235
tot_pkt_len          -0.020349
fwd_pkt_len          -0.014275
bwd_pkt_len          -0.011923
dtype: float64

In [25]:
df_voip.corrwith(df_streaming)

avg(pkt_len)         -0.021086
stddev(pkt_len)       0.051080
fb_ratio             -0.019747
inter_arrival_time   -0.004553
pkt_count            -0.006604
duration              0.183291
tot_pkt_len           0.023449
fwd_pkt_len          -0.006034
bwd_pkt_len          -0.014726
dtype: float64

In [42]:
df_voip.corrwith(df_game)

avg(pkt_len)          0.025837
stddev(pkt_len)       0.065221
fb_ratio              0.019417
inter_arrival_time    0.029667
pkt_count            -0.006191
duration              0.010463
tot_pkt_len          -0.017436
fwd_pkt_len          -0.001732
bwd_pkt_len          -0.015900
dtype: float64

In [27]:
df_streaming.corrwith(df_game)

avg(pkt_len)         -0.146467
stddev(pkt_len)       0.031382
fb_ratio             -0.065174
inter_arrival_time   -0.011299
pkt_count            -0.010384
duration              0.024908
tot_pkt_len          -0.074869
fwd_pkt_len           0.026274
bwd_pkt_len          -0.040055
dtype: float64